console.log(typeof 1)
console.log(typeof '1')
console.log(typeof Symbol('1'))
console.log(typeof true)
console.log(typeof undefined)
console.log(typeof null)
console.log(typeof function (){})
console.log(typeof {})
console.log(typeof NaN)
console.log(typeof [])
console.log([] instanceof Array)
console.log([] instanceof Object)